steps:
  # Step 1 — build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/engage-via-dm-repo/engage-via-dm-be:$COMMIT_SHA'
      - '.'

  # Step 2 — push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/engage-via-dm-repo/engage-via-dm-be:$COMMIT_SHA'

  # Step 3 — deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'engage-via-dm-be'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/engage-via-dm-repo/engage-via-dm-be:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=DATABASE_URL=RABBITMQ_URL:latest,DATABASE_URL:latest,INSTA_APP_CLIENT_ID=INSTA_APP_CLIENT_ID:latest,INSTA_APP_CLIENT_SECRET=INSTA_APP_CLIENT_SECRET:latest,INSTA_APP_REDIRECT_URI=INSTA_APP_REDIRECT_URI:latest,FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,FIREBASE_CLIENT_EMAIL=FIREBASE_CLIENT_EMAIL:latest,FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest,REDIS_URL=REDIS_URL:latest'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/engage-via-dm-repo/engage-via-dm-be:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY